### ISSUE TITLE
Question: Is FP8-LM only supported on H100?

### ISSUE THREAD

**Issue by LSC527** [Azure/MS-AMP#116]
Can it run on A100?

**Comment by chinoll** [comment]
same question

**Comment by wkcn** [comment]
Hi @LSC527  and @chinoll ,
Thank you for your interest in our work!

MS-AMP offers support for NVIDIA V100, A100, and H100 GPUs with CUDA 11.8 or higher version.
We provide a docker image with the latest version of MS-AMP: `ghcr.io/azure/msamp:latest`

For V100 and A100 GPUs, the FP8 data format is not native but simulated in CUDA 11.8+. We utilize [FP16/BF16 GEMM](https://github.com/Azure/MS-AMP/blob/main/msamp/operators/gemm/gemm.py#L148) to compute the linear layer. While it is slower than BF16 mixed precision, it still save GPU memory like H100.

**Comment by LSC527** [comment]
@wkcn Got it. Thanks for your reply.

**Comment by wpf19911118** [comment]
When I use ghcr.io/azure/msamp:main-cuda12.1 docker images in A800 , It seems run error:
Traceback (most recent call last):
  File "../third_party/Megatron-LM/pretrain_gpt.py", line 119, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/training.py", line 159, in pretrain
    iteration = train(forward_step_func,
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/training.py", line 764, in train
    train_step(forward_step_func,
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/training.py", line 454, in train_step
    losses_reduced = forward_backward_func(
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 329, in forward_backward_no_pipelining
    output_tensor = forward_step(
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 185, in forward_step
    output_tensor, loss_func = forward_step_func(data_iterator, model)
  File "../third_party/Megatron-LM/pretrain_gpt.py", line 88, in forward_step
    output_tensor = model(tokens, position_ids, attention_mask,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/model/distributed.py", line 58, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/model/module.py", line 181, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/model/gpt_model.py", line 82, in forward
    lm_output = self.language_model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/model/language_model.py", line 501, in forward
    encoder_output = self.encoder(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sa/LLM_test/MS-AMP-Examples/third_party/Megatron-LM/megatron/model/transformer.py", line 1643, in forward
    with transformer_engine.pytorch.fp8_autocast(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/fp8.py", line 299, in fp8_autocast
    assert fp8_available, reason_for_no_fp8
AssertionError: Device compute capability 8.9 or higher required for FP8 execution.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3713) of binary: /usr/bin/python

**Comment by wkcn** [comment]
Hi @wpf19911118 ,
TransformerEngine-FP8 does not support on A800. You can remove the following two arguments:
```bash
        --fp8-hybrid \
        --transformer-impl transformer_engine \
```
in https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/pretrain_345m_megatron.sh#L100C1-L101C48

Then FP8Linear in MS-AMP will be used.
