### ISSUE TITLE
[Question]Is MS-AMP going to support ZeRO-2 + PP ?

### ISSUE THREAD

**Issue by ohwi** [Azure/MS-AMP#154]
https://github.com/Azure/MS-AMP/blob/2fbe8985d83669e593c79e04282af988714e3472/msamp/deepspeed/runtime/pipe/engine.py#L14-L29

The comment of the function says `Pipeline engine supports pipeline+ZeRO-2+BF16.`, but it's not implemented.

When I tried zero stage 2 without bf16, with fp16 for example, I got the error as that of deepspeed:

```
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    train_pipe(args)
  File "train.py", line 97, in train_pipe
    engine, _, _, _ = deepspeed.initialize(
  File "/usr/local/lib/python3.8/dist-packages/msamp/deepspeed/__init__.py", line 152, in initialize
    engine = MSAMPPipelineEngine(
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/pipe/engine.py", line 58, in __init__
    assert self.zero_optimization_stage() < 2, "ZeRO-2 and ZeRO-3 are incompatible with pipeline parallelism"
AssertionError: ZeRO-2 and ZeRO-3 are incompatible with pipeline parallelism
```

Here's the code that I tried. I followed #81 with little change to follow v0.3.0. ZeRO-1 + PP worked with this code.

```
#!/usr/bin/env python3

import os
import argparse

import torch
import torch.distributed as dist

import torchvision
import torchvision.transforms as transforms
from torchvision.models import AlexNet
from torchvision.models import vgg19

from deepspeed import PipelineModule
from msamp import deepspeed


def cifar_trainset(local_rank, dl_path='/tmp/cifar10-data'):
    transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.ConvertImageDtype(dtype=torch.bfloat16),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    # Ensure only one rank downloads.
    # Note: if the download path is not on a shared filesytem, remove the semaphore
    # and switch to args.local_rank
    dist.barrier()
    if local_rank != 0:
        dist.barrier()
    trainset = torchvision.datasets.CIFAR10(root=dl_path,
                                            train=True,
                                            download=True,
                                            transform=transform)
    if local_rank == 0:
        dist.barrier()
    return trainset

def get_args():
    parser = argparse.ArgumentParser(description='CIFAR')
    parser.add_argument('--local_rank',
                        type=int,
                        default=-1,
                        help='local rank passed from distributed launcher')
    parser.add_argument('-s',
                        '--steps',
                        type=int,
                        default=100,
                        help='quit after this many steps')
    parser.add_argument('-p',
                        '--pipeline-parallel-size',
                        type=int,
                        default=2,
                        help='pipeline parallelism')
    parser.add_argument('--backend',
                        type=str,
                        default='nccl',
                        help='distributed backend')
    parser.add_argument('--seed', type=int, default=1138, help='PRNG seed')
    parser = deepspeed.add_config_arguments(parser)
    args = parser.parse_args()
    return args


def join_layers(vision_model):
    layers = [
        *vision_model.features,
        vision_model.avgpool,
        lambda x: torch.flatten(x, 1),
        *vision_model.classifier,
    ]
    return layers


def train_pipe(args, part='parameters'):
    torch.manual_seed(args.seed)
    # deepspeed.runtime.utils.set_random_seed(args.seed)
    #
    # Build the model
    #

    # VGG also works :-)
    #net = vgg19(num_classes=10)
    net = AlexNet(num_classes=10)
    net = PipelineModule(layers=join_layers(net),
                         loss_fn=torch.nn.CrossEntropyLoss(),
                         num_stages=args.pipeline_parallel_size,
                         partition_method=part,
                         activation_checkpoint_interval=0)

    trainset = cifar_trainset(args.local_rank)

    engine, _, _, _ = deepspeed.initialize(
        args=args,
        model=net,
        model_parameters=[p for p in net.parameters() if p.requires_grad],
        training_data=trainset)

    for step in range(args.steps):
        loss = engine.train_batch()


if __name__ == '__main__':
    args = get_args()

    deepspeed.init_distributed(dist_backend=args.backend)
    args.local_rank = int(os.environ['LOCAL_RANK'])
    torch.cuda.set_device(args.local_rank)

    if args.pipeline_parallel_size == 0:
        train_base(args)
    else:
        train_pipe(args)
```

Is there any plan to support ZeRO-2 + PP in MS-AMP roadmap? Or is ZeRO-2 + PP impossible empirically or theoretically?

**Comment by ohwi** [comment]
I found that ZeRO-2 and PP are incompatible. Thank you.
